// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.PeekSteps.Integration.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature : Xunit.IClassFixture<PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PreviousNextThroughScenarioStepContext.feature"
#line hidden
        
        public PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Previous and next steps are accessed through ScenarioStepContext", "\tIn order to hook into interesting events\r\n\tAs a SpecFlow statement writer\r\n\tI wa" +
                    "nt to be have access to steps in BeforeStep hook", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Previous and next steps are accessed through ScenarioStepContext")]
        [Xunit.TraitAttribute("FeatureTitle", "Previous and next steps are accessed through ScenarioStepContext")]
        [Xunit.TraitAttribute("Description", "Previous and next steps are accessed through ScenarioStepContext")]
        [Xunit.TraitAttribute("Category", "enable-peeking")]
        public virtual void PreviousAndNextStepsAreAccessedThroughScenarioStepContext()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Previous and next steps are accessed through ScenarioStepContext", new string[] {
                        "enable-peeking"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I have a simple given statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I have a another simple given statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("I successfully enquire about the current statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("I successfully enquire about the next statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I successfully enquire about the previous statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I have a simple then statement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Previous and next steps are null in boundary case when accessed through ScenarioS" +
            "tepContext")]
        [Xunit.TraitAttribute("FeatureTitle", "Previous and next steps are accessed through ScenarioStepContext")]
        [Xunit.TraitAttribute("Description", "Previous and next steps are null in boundary case when accessed through ScenarioS" +
            "tepContext")]
        [Xunit.TraitAttribute("Category", "enable-peeking")]
        public virtual void PreviousAndNextStepsAreNullInBoundaryCaseWhenAccessedThroughScenarioStepContext()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Previous and next steps are null in boundary case when accessed through ScenarioS" +
                    "tepContext", new string[] {
                        "enable-peeking"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I have a simple given statement with previous step as null", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
 testRunner.Then("I have a simple then statement with next step as null", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PreviousAndNextStepsAreAccessedThroughScenarioStepContextFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
